#!/bin/bash

MOUNT_VOLUME='/nubis/data'
WORKING_PATH='/nubis/work'
TERRAFORM_PATH="${WORKING_PATH}/nubis/terraform"

# Make sure we capture failures from pipe commands
set -o pipefail

show_help () {
    echo -en "\nUsage:docker run --interactive --tty --env-file ~/.docker_env -v $PWD:/nubis/data nubis-deploy [command]\n\n"
    echo -en "Commands:\n"
    echo -en "  --help     Print this help message\n\n"
    echo -en "  plan       Show the deployment plan\n\n"
    echo -en "  apply      Apply the deployment\n\n"
    echo -en "  destroy    Destroy the deployment\n"
    echo -en "  show       Show the state of the deployment\n"
    echo -en "  output     Display outputs for the deployment\n"
    echo -en "  state      Work with the state of the deployment\n"
    exit 0
}

setup-deploy-dir () {
    # Skip any downloaded terraform submodules.
    #+ Terraform modules contain symlinks with full paths that are not valid in
    #+ the container.
    # Skip the nubis directory, we do not want it in the doc root
    RSYNC=( 'rsync' '-auz' )
    RSYNC_EXCLUDES=(  '--exclude=SEC,*.pid' )
    RSYNC_EXCLUDES+=('--exclude=.terraform' )
    RSYNC_EXCLUDES+=( '--exclude=.git*' )
    RSYNC_EXCLUDES+=( '--exclude=.travis.yml' )
    RSYNC_EXCLUDES+=( '--exclude=terraform.tfstate*' )
    "${RSYNC[@]}" "${RSYNC_EXCLUDES[@]}" -x "${MOUNT_VOLUME}/" "${WORKING_PATH}/"
}

setup-terraform () {
    ACCOUNT=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .account ); export ACCOUNT
    ENVIRONMENT=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .environment ); export ENVIRONMENT
    DEPLOYMENT_REGION=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .region ); export DEPLOYMENT_REGION
    SERVICE_NAME=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .service_name ); export SERVICE_NAME
    STATE_BUCKET=$(curl -s "http://state.nubis.${ACCOUNT}.nubis.allizom.org/aws/${DEPLOYMENT_REGION}/${ENVIRONMENT}.tfstate" | \
        jq -r ' .modules[] | select(.path == ["root"]) | .outputs.apps_state_bucket'); export STATE_BUCKET
    BUCKET_REGION=$(aws s3api get-bucket-location --bucket "${STATE_BUCKET}" | jq -r '.LocationConstraint'); export BUCKET_REGION

    cd "${TERRAFORM_PATH}" && terraform init \
        -input=true \
        -upgrade=false \
        -backend-config="region=${BUCKET_REGION}" \
        -backend-config="key=terraform/${SERVICE_NAME}" \
        -backend-config="bucket=${STATE_BUCKET}"
    if [ "$?" != 0 ]; then
        echo "ERROR: Could not initialize teraform"
        exit 1
    fi
}

terraform-apply () {
    cd "${TERRAFORM_PATH}" && terraform plan -out="terraform.plan"

    if [ "$?" != 0 ]; then
        echo "Terraform plan failed. Not applying plan."
        exit 1
    fi

    cd "${TERRAFORM_PATH}" && terraform apply "terraform.plan"

    # Copy Terraform files to the S3 bucket
    echo -e "\nUploading Terraform assets to s3"
    aws s3 sync --delete --region "${BUCKET_REGION}" --exclude ".terraform*" "${TERRAFORM_PATH}/" "s3://${STATE_BUCKET}/terraform/${SERVICE_NAME}-terraform/"
}

terraform-do () {
    declare -a _ACTION; _ACTION=( ${@} )
    cd "${TERRAFORM_PATH}"  && terraform "${_ACTION[@]}"
}

# Grab and setup called options
while [ "$1" != "" ]; do
    case $1 in
        --help )
            show_help
        ;;
        plan )
            setup-deploy-dir
            setup-terraform
            terraform-do plan
        ;;
        apply )
            setup-deploy-dir
            setup-terraform
            terraform-apply
        ;;
        destroy )
            setup-deploy-dir
            setup-terraform
            terraform-do destroy
        ;;
        show )
            setup-deploy-dir
            setup-terraform
            terraform-do show
        ;;
        output )
            shift
            setup-deploy-dir
            setup-terraform
            terraform-do output "${@}"
        ;;
        state )
            shift
            setup-deploy-dir
            setup-terraform
            terraform-do state "${@}"
        ;;
        * )
            show_help
        ;;
    esac
    shift
done
