#!/bin/bash

MOUNT_VOLUME='/nubis/data'
WORKING_PATH='/nubis/work'
TERRAFORM_PATH="${WORKING_PATH}/nubis/terraform"

# Make sure we capture failures from pipe commands
set -o pipefail

show_help () {
    echo -en "\nUsage:docker run --interactive --tty --env-file ~/.docker_env -v $PWD:/nubis/data nubis-deploy [command]\n\n"
    echo -en "Commands:\n"
    echo -en "  --help     Print this help message\n\n"
    echo -en "  plan       Show the deployment plan\n\n"
    echo -en "  apply      Apply the deployment\n\n"
    echo -en "  destroy    Destroy the deployment\n"
    echo -en "  show       Show the state of the deployment\n"
    echo -en "  output     Display outputs for the deployment\n"
    echo -en "  state      Work with the state of the deployment\n"
    exit 0
}

setup-deploy-dir () {
    # Skip any downloaded terraform submodules.
    #+ Terraform modules contain symlinks with full paths that are not valid in
    #+ the container.
    # Skip the nubis directory, we do not want it in the doc root
    RSYNC=( 'rsync' '-auz' )
    RSYNC_EXCLUDES=(  '--exclude=SEC,*.pid' )
    RSYNC_EXCLUDES+=('--exclude=.terraform' )
    RSYNC_EXCLUDES+=( '--exclude=.git*' )
    RSYNC_EXCLUDES+=( '--exclude=.travis.yml' )
    RSYNC_EXCLUDES+=( '--exclude=terraform.tfstate*' )
    if ! "${RSYNC[@]}" "${RSYNC_EXCLUDES[@]}" -x "${MOUNT_VOLUME}/" "${WORKING_PATH}/" ; then
        echo -e "\033[1;31mERROR: Failed to rsync files\033[0m"
        exit 1
    fi
}

setup-terraform () {
    # Test for the existance of the variables file
    if [ ! -f "${TERRAFORM_PATH}/terraform.tfvars" ]; then
        echo -e "\033[1;31mERROR: 'terraform.tfvars' file not found in ${TERRAFORM_PATH}\033[0m"
        exit 1
    fi

    # Test for the existance of state.tf file
    if [ ! -f "${TERRAFORM_PATH}/state.tf" ];then
        echo -e "\033[1;31mERROR: 'state.tf' file not found in ${TERRAFORM_PATH}\033[0m"
        echo -e "\033[1;31mERROR: 'state.tf' file should contain the following lines:\033[0m"
        echo -e "\033[1;31mERROR: terraform { backend "s3" {} }\033[0m"
        exit 1
    fi

    ACCOUNT=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .account )
    # Make sure we got an account name
    if [ "${ACCOUNT}" == 'null' ]; then
        echo -e "\033[1;31mERROR: 'account' not set ${TERRAFORM_PATH}/terraform.tfvars\033[0m"
        exit 1
    else
        export ACCOUNT
    fi
    ARENA=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .arena )
    # Make sure we got an arena
    if [ "${ARENA}" == 'null' ]; then
        echo -e "\033[0;32mWARNING: 'arena' not set ${TERRAFORM_PATH}/terraform.tfvars\033[0m"
        echo -e "\033[0;32mWARNING: Defaulting 'arena' to 'core'\033[0m"
        echo -e "\033[0;32mWARNING: 'arena' will be required in a future release\033[0m"
        ARENA='core'; export ARENA
    else
        export ARENA
    fi
    DEPLOYMENT_REGION=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .region )
    # Make sure we got a deployment region
    if [ "${DEPLOYMENT_REGION}" == 'null' ]; then
        echo -e "\033[1;31mERROR: 'region' not set ${TERRAFORM_PATH}/terraform.tfvars\033[0m"
        exit 1
    else
        export DEPLOYMENT_REGION
    fi
    SERVICE_NAME=$(toml2json < "${TERRAFORM_PATH}/terraform.tfvars" | jq -r .service_name )
    # Make sure we got a service name
    if [ "${SERVICE_NAME}" == 'null' ]; then
        echo -e "\033[1;31mERROR: 'service_name' not set ${TERRAFORM_PATH}/terraform.tfvars\033[0m"
        exit 1
    else
        export SERVICE_NAME
    fi
    STATE_BUCKET=$(curl -s "http://state.nubis.${ACCOUNT}.nubis.allizom.org/aws/${DEPLOYMENT_REGION}/${ARENA}.tfstate" | \
        jq -r ' .modules[] | select(.path == ["root"]) | .outputs.apps_state_bucket')
    # Make sure we have a state bucket
    if [ "${STATE_BUCKET}" == 'null' ] || [ -z "${STATE_BUCKET}" ]; then
        echo -e "\033[1;32mWARNING: Could not find state bucket in account '${ARENA}.tfstate' file using:\033[0m"
        echo -e "\033[1;32mWARNING: 'curl -s \"http://state.nubis.${ACCOUNT}.nubis.allizom.org/aws/${DEPLOYMENT_REGION}/${ARENA}.tfstate\"'\033[0m"

        # Default checking state bucket using awscli
        echo -e "\033[0;32mWARNING: Defaulting state bucket discovery in S3 using awscli\033[0m"
        STATE_BUCKET=$(aws s3 ls | grep nubis-apps-state | awk '{print $3}')
        if [ "${STATE_BUCKET}" == 'null' ] || [ -z "${STATE_BUCKET}" ]; then
            echo -e "\033[1;31mERROR: Could not find S3 state bucket using:\033[0m"
            echo -e "\033[1;31mERROR: 'aws s3 ls | grep nubis-apps-state | awk \"{ print \$3 }\"'\033[0m"
            exit 1
        else
            export STATE_BUCKET
        fi

    else
        export STATE_BUCKET
    fi
    BUCKET_REGION=$(aws s3api get-bucket-location --bucket "${STATE_BUCKET}" | jq -r '.LocationConstraint')
    # Make sure we got a state bucker region
    if [ "${BUCKET_REGION}" == 'null' ]; then
        echo -e "\033[1;31mERROR: Could not look up bucket location using:\033[0m"
        echo -e "\033[1;31mERROR: 'aws s3api get-bucket-location --bucket \"${STATE_BUCKET}\"'\033[0m"
        exit 1
    else
        export BUCKET_REGION
    fi

    if ! cd "${TERRAFORM_PATH}" ; then
        echo -e "\033[1;31mERROR: Could not cd into '${TERRAFORM_PATH}'\033[0m"
        exit 1
    fi

    if ! terraform init \
        -input=true \
        -upgrade=false \
        -backend-config="region=${BUCKET_REGION}" \
        -backend-config="key=terraform/${SERVICE_NAME}" \
        -backend-config="bucket=${STATE_BUCKET}" ;
    then
        echo -e "\033[1;31mERROR: Could not initialize teraform\033[0m"
        exit 1
    fi
}

terraform-apply () {
    if ! cd "${TERRAFORM_PATH}" ; then
        echo -e "\033[1;31mERROR: Could not cd into '${TERRAFORM_PATH}'\033[0m"
        exit 1
    fi

    if ! terraform plan -out="terraform.plan" ; then
        echo -e "\033[1;31mERROR: Terraform plan failed. Not applying plan\033[0m"
        exit 1
    fi

    terraform apply "terraform.plan"

    # Copy Terraform files to the S3 bucket
    echo -e "\nUploading Terraform assets to s3"
    aws s3 sync --delete --region "${BUCKET_REGION}" --exclude ".terraform*" "${TERRAFORM_PATH}/" "s3://${STATE_BUCKET}/terraform/${SERVICE_NAME}-terraform/"
}

terraform-do () {
    declare -a _ACTION; _ACTION=( ${@} )
    cd "${TERRAFORM_PATH}"  && terraform "${_ACTION[@]}"
}

# Grab and setup called options
while [ "$1" != "" ]; do
    case $1 in
        --debug )
            set -x
        ;;
        --help )
            show_help
        ;;
        plan )
            setup-deploy-dir
            setup-terraform
            terraform-do plan
        ;;
        apply )
            setup-deploy-dir
            setup-terraform
            terraform-apply
        ;;
        destroy )
            setup-deploy-dir
            setup-terraform
            terraform-do destroy
        ;;
        show )
            setup-deploy-dir
            setup-terraform
            terraform-do show
        ;;
        output )
            shift
            setup-deploy-dir
            setup-terraform
            terraform-do output "${@}"
        ;;
        state )
            shift
            setup-deploy-dir
            setup-terraform
            terraform-do state "${@}"
        ;;
        * )
            show_help
        ;;
    esac
    shift
done
